server:
  port: 8081
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:h2:./myDb.data
  jpa:
    hibernate:
      ddl-auto: create
javax:
  persistence:
    schema-generation:
      scripts:
        action: create